spring.application.name=printrequest-service
spring.datasource.url=jdbc:postgresql://localhost:5432/prms
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8081
spring.security.user.name=admin
spring.security.user.password=admin

spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=true
eureka.client.enabled=false
