spring.application.name=user-service

spring.security.user.name=admin
spring.security.user.password=admin





keycloak.realm=spring-microservices-security-realm
<<<<<<< Updated upstream

keycloak.auth-server-url=http://localhost:9000
=======
keycloak.client-id=spring-client-credentials-id
>>>>>>> Stashed changes
keycloak.resource=spring-client-credentials-id
keycloak.credentials.secret=pwRiTf6kGrcHNQpWXiL6fkjIY0cP6WUx
keycloak.use-resource-role-mappings=true


keycloak.publickey=-----BEGIN PUBLIC KEY-----\
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0M12V3I/xlGfJFwIPx7Ys0HQmpV7wkmxMxK1yTfFMt06iQ0eYWYrCPeODjqfmT5Z9MzQvooH+cXKdp6bdgepygR0kfEPWofSkN5Ej+vhia/c6QYpgBOtSM/dLhtWlFaTihI75Dedp5Lak+shtbWkADidVVNJM1kolkCahES2M30WFhu31DGzBExd68AN1B3HaMjsG9qwmqBKx+O3gIYqt4WdsdC/Ta9cdGbK1TVAETMggbI8/zOm5hpzlpYzHbPR88HAF//AWWuQXbsCDTEoY4UyRrXN7Sh/EJyrSvHwwT+uKHJUkKrhneUzqiqS4hK3kvhAuIKshStu/bMmyNMWcwIDAQAB\
 -----END PUBLIC KEY-----





#spring.datasource.url=jdbc:mysql://localhost:3306/prms
spring.datasource.url=jdbc:postgresql://localhost:5432/prms

spring.datasource.username=postgres
spring.datasource.password=242619
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.secret.key=a2P1MfLtUss3joijeGzYLPXcPhsySuYAb9MSg5mWkdg=
app.secret.otp.key = ch7ZwAD0MfdSebCtrn7c9Gsneg/JqNxtwY5qCaFU1T8=
app.encrytion.algo=AES/CBC/PKCS5Padding
spring.jpa.hibernate.ddl-auto=update

<<<<<<< Updated upstream

#Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=souihiraached@gmail.com
spring.mail.password=zxnexbktkwkbflna
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true






# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Producer serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Trust the package where KafkaEvent is located
spring.kafka.producer.properties.spring.json.trusted.packages=com.microservices.user_service.service





=======
>>>>>>> Stashed changes
