spring.application.name=user-service

spring.security.user.name=admin
spring.security.user.password=admin





server.port= 8081


keycloak.realm=spring-microservices-security-realm

keycloak.auth-server-url=http://localhost:8180
keycloak.resource=spring-client-credentials-id
keycloak.credentials.secret=pwRiTf6kGrcHNQpWXiL6fkjIY0cP6WUx
keycloak.use-resource-role-mappings=true


keycloak.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtbozve3F6DPixrSmrJ/t4ibgEFxc/mA47nlZD9+TEjzyH2bWbBeFQy1GsF/V4YKE5MmJUplGwkI7TGSiS62j1LbVmTX3ni8Hpps1+OzQykAOV21rkm9Rgt6mv7YqWRYeMp7srqciddLDyUBlttS/4ZGVQpLvCXmhmx1U/57Yl059dagQs2L1GUPmD74TlkkYFLZQR0BcgfrnhGO/bqjkeQ13wCRkldkbtcXvUGQ547gnmord5G/z9nZtGGkyfbehRcZUL1hyrO3nwridEw0T4Klg1dx+migtOEMeSn8DZCU1mwsXvJKc2n8M4KtNQJiOKqObc7QnfhqeKuFJf8n1DQIDAQAB





#spring.datasource.url=jdbc:mysql://localhost:3306/prms
spring.datasource.url=jdbc:postgresql://localhost:5432/prms

spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

app.secret.key=a2P1MfLtUss3joijeGzYLPXcPhsySuYAb9MSg5mWkdg=
app.secret.otp.key = ch7ZwAD0MfdSebCtrn7c9Gsneg/JqNxtwY5qCaFU1T8=
app.encrytion.algo=AES/CBC/PKCS5Padding
spring.jpa.hibernate.ddl-auto=update


#Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6380

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jahmichaima333@gmail.com
spring.mail.password=oubsbfxrtqjohuwf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true






# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.auto-offset-reset=earliest


# Producer serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Trust the package where KafkaEvent is located
spring.kafka.producer.properties.spring.json.trusted.packages=com.microservices.user_service.service

security.permitted-paths=/user/get-all-users, /user/**