spring.application.name=user-service

eureka.client.enabled=false
spring.security.user.name=admin
spring.security.user.password=admin


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=8081