spring.application.name=profile-service
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8087

spring.security.user.name=admin
spring.security.user.password=admin
app.secret.key=a2P1MfLtUss3joijeGzYLPXcPhsySuYAb9MSg5mWkdg=
app.encrytion.algo=AES/CBC/PKCS5Padding


security.permitted-paths=/ws/**, /user/get-all-users, /broadcast/test-notif
eureka.client.enabled=false