spring.application.name=api-gateway

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=8085

keycloak.realm=spring-microservices-security-realm


keycloak.auth-server-url=http://localhost:8180
keycloak.resource=spring-client-credentials-id
keycloak.credentials.secret=NV5hwoamSBfPYxN70xIkd5QYXsz8JNf8
keycloak.use-resource-role-mappings=true


keycloak.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtbozve3F6DPixrSmrJ/t4ibgEFxc/mA47nlZD9+TEjzyH2bWbBeFQy1GsF/V4YKE5MmJUplGwkI7TGSiS62j1LbVmTX3ni8Hpps1+OzQykAOV21rkm9Rgt6mv7YqWRYeMp7srqciddLDyUBlttS/4ZGVQpLvCXmhmx1U/57Yl059dagQs2L1GUPmD74TlkkYFLZQR0BcgfrnhGO/bqjkeQ13wCRkldkbtcXvUGQ547gnmord5G/z9nZtGGkyfbehRcZUL1hyrO3nwridEw0T4Klg1dx+migtOEMeSn8DZCU1mwsXvJKc2n8M4KtNQJiOKqObc7QnfhqeKuFJf8n1DQIDAQAB


spring.security.user.name=admin
spring.security.user.password=admin




app.secret.key=a2P1MfLtUss3joijeGzYLPXcPhsySuYAb9MSg5mWkdg=
app.encrytion.algo=AES/CBC/PKCS5Padding


security.permitted-paths=/ws/**, /user/get-all-users, /broadcast/test-notif