spring.application.name=api-gateway

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=9001

keycloak.realm=spring-microservices-security-realm

keycloak.auth-server-url=http://localhost:9000
keycloak.resource=spring-client-credentials-id
keycloak.credentials.secret=pwRiTf6kGrcHNQpWXiL6fkjIY0cP6WUx
keycloak.use-resource-role-mappings=true

spring.security.user.name=admin
spring.security.user.password=admin


keycloak.publickey=-----BEGIN PUBLIC KEY-----\
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0M12V3I/xlGfJFwIPx7Ys0HQmpV7wkmxMxK1yTfFMt06iQ0eYWYrCPeODjqfmT5Z9MzQvooH+cXKdp6bdgepygR0kfEPWofSkN5Ej+vhia/c6QYpgBOtSM/dLhtWlFaTihI75Dedp5Lak+shtbWkADidVVNJM1kolkCahES2M30WFhu31DGzBExd68AN1B3HaMjsG9qwmqBKx+O3gIYqt4WdsdC/Ta9cdGbK1TVAETMggbI8/zOm5hpzlpYzHbPR88HAF//AWWuQXbsCDTEoY4UyRrXN7Sh/EJyrSvHwwT+uKHJUkKrhneUzqiqS4hK3kvhAuIKshStu/bMmyNMWcwIDAQAB\
 -----END PUBLIC KEY-----

app.secret.key=a2P1MfLtUss3joijeGzYLPXcPhsySuYAb9MSg5mWkdg=
app.encrytion.algo=AES/CBC/PKCS5Padding


security.permitted-paths=/ws/**, /user/get-all-users, /broadcast/test-notif